<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" />
    <PackageReference Include="TUnit" />
    <ProjectReference Include="..\..\src\Novolis.Commands.Queueing\Novolis.Commands.Queueing.csproj" />
    <ProjectReference Include="..\..\src\Novolis.Commands.Testing\Novolis.Commands.Testing.csproj" />
  </ItemGroup>
</Project>
